annotation_route:
    resource: "@AppBundle/Controller/"
    type:     annotation    

yaml_route:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /member
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
admin_user_index:
    path: /admin/user
    defaults: { _controller: "AppBundle:Admin:index" }

admin_user_show:
    path: /admin/user/{id}/show
    defaults: { _controller: "AppBundle:Admin:show" }

admin_user_edit:
    path: /admin/user/{id}/edit
    defaults: { _controller: "AppBundle:Admin:edit" }

admin_user_delete:
    path:     /admin/user/{id}/delete
    defaults: { _controller: "AppBundle:Admin:delete" }
    methods:  DELETE

app_admin_role:
    resource: "@AppBundle/Resources/config/routing/role.yml"
    prefix:   /admin/role
    
app_admin_csvfiles:
    resource: "@AppBundle/Resources/config/routing/csvfiles.yml"
    prefix:   /admin/csvfiles   

